[build-system]
requires = [
    "setuptools",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "piperformance"
readme = "README.md"
version = "0.1.0"
dependencies = [
    "tqdm",
]

[tool.setuptools]
py-modules = ["piperformance"]
